### ISSUE TITLE
could not load correctly

### ISSUE THREAD

**Issue by kidc2458** [MBulli/SmartCommandlineArgs#176]
hello. We are very pleased with the release of version 3.0.
I shared the release of the new version with my colleagues, and some of them reported that the extension did not run after installation on their PCs.

```
Exception details:
System.IO.FileNotFoundException: 지정된 파일을 찾을 수 없습니다. (Exception from HRESULT: 0x80070002)
   at Microsoft.VisualStudio.Shell.Interop.IVsShell5.LoadPackageWithContext(Guid& packageGuid, Int32 reason, Guid& context)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.GetPackage()
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.ConstructContent()
```

Perhaps some required package isn't installed on my coworker's PC, but I can't figure out what it is.
It is said to run normally when version 2.6 is installed.
Perhaps the necessary packages were added in 3.0.

**Comment by Irame** [comment]
Hi, could you please try [v3.0.1](https://github.com/MBulli/SmartCommandlineArgs/releases/tag/v3.0.1) and see if the issue persists on your colleagues machines?
